'use strict';
const $=s=>document.querySelector(s),clamp=(v,min,max)=>Math.min(max,Math.max(min,v));
const SETTINGS_KEY='teleprompter.settings.v3',TEXT_KEY='teleprompter.currentText.v3',HISTORY_KEY='teleprompter.history.v3';
const WPM=[0,100,140,190,250,320,400,500,620,760,900],defaults={speed:4,font:36,line:1.4,margin:20,cue:50,upper:true,mirror:false};
const editor=$('#editor'),reader=$('#reader'),scrollArea=$('#scroll'),playButton=$('#play'),historyButton=$('#historyButton'),historyPopover=$('#historyPopover'),helpButton=$('#helpButton'),helpPopover=$('#helpPopover');
function readJSON(k,f){try{return JSON.parse(localStorage.getItem(k)||'')||f}catch{return f}}
const legacy=readJSON('tp2',{}),stored=readJSON(SETTINGS_KEY,null)||{speed:legacy.speed,font:legacy.font,line:legacy.line,margin:legacy.margin,cue:legacy.cue,upper:legacy.upper,mirror:legacy.mirror};
const state={...defaults,...Object.fromEntries(Object.entries(stored||{}).filter(([,v])=>v!==undefined)),text:localStorage.getItem(TEXT_KEY)??legacy.text??'',running:false,lastFrame:0,carry:0,exitAnchor:null};
let history=readJSON(HISTORY_KEY,readJSON('tpHistory',[]));
function saveSettings(){try{localStorage.setItem(SETTINGS_KEY,JSON.stringify({speed:state.speed,font:state.font,line:state.line,margin:state.margin,cue:state.cue,upper:state.upper,mirror:state.mirror}))}catch{}}
function saveText(){try{localStorage.setItem(TEXT_KEY,state.text)}catch{}}
function saveHistory(){history=history.slice(0,12);try{localStorage.setItem(HISTORY_KEY,JSON.stringify(history))}catch{history=history.slice(0,6);try{localStorage.setItem(HISTORY_KEY,JSON.stringify(history))}catch{}}}
function countWords(t=state.text){const c=t.trim();return c?c.split(/\s+/).length:0}
function totalSeconds(){return countWords()/WPM[state.speed]*60}
function formatDuration(s){if(!s||!Number.isFinite(s))return'0s';const r=Math.max(1,Math.round(s)),m=Math.floor(r/60),x=r%60;return m?(x?`${m}min ${x}s`:`${m}min`):`${x}s`}
function updateStats(){const w=countWords();$('#stats').textContent=`${w} ${w===1?'palavra':'palavras'} · ${formatDuration(totalSeconds())}`;$('#speed').textContent=state.speed;$('#speed').title=`${WPM[state.speed]} palavras por minuto`}
function renderText(){const c=state.text.trim();if(!c)reader.innerHTML='<p class="empty">Seu roteiro aparece aqui.</p>';else reader.replaceChildren(...c.split(/\n\s*\n/).map(par=>{const p=document.createElement('p');par.split('\n').forEach((line,i)=>{if(i)p.append(document.createElement('br'));p.append(document.createTextNode(line))});return p}));updateStats();updateProgress()}
function applySettings(){const r=document.documentElement.style;r.setProperty('--reader-size',`${state.font}px`);r.setProperty('--reader-line',state.line);r.setProperty('--reader-margin',`${state.margin}vw`);r.setProperty('--cue',`${state.cue}%`);reader.classList.toggle('upper',state.upper);reader.classList.toggle('mirror',state.mirror);$('#font').value=state.font;$('#line').value=state.line.toFixed(2);$('#margin').value=state.margin;$('#cueOut').value=state.cue;$('#upper').checked=state.upper;$('#mirror').checked=state.mirror;updateStats()}
function updateProgress(){const m=scrollArea.scrollHeight-scrollArea.clientHeight;$('#progress').style.width=`${m?clamp(scrollArea.scrollTop/m*100,0,100):0}%`}
function setRunning(v){state.running=Boolean(v)&&countWords()>0;playButton.textContent=state.running?'Ⅱ':'▶';playButton.setAttribute('aria-label',state.running?'Pausar':'Iniciar');if(state.running&&'wakeLock'in navigator)navigator.wakeLock.request('screen').catch(()=>{})}
function pixelsPerSecond(){const max=scrollArea.scrollHeight-scrollArea.clientHeight,d=totalSeconds();return d>0?max/d:0}
function frame(t){const dt=Math.min(40,t-(state.lastFrame||t));state.lastFrame=t;if(state.running){state.carry+=pixelsPerSecond()*dt/1000;if(state.carry>=1){const move=Math.floor(state.carry);scrollArea.scrollTop+=move;state.carry-=move;updateProgress()}if(scrollArea.scrollTop+scrollArea.clientHeight>=scrollArea.scrollHeight-2)setRunning(false)}requestAnimationFrame(frame)}
function changeSpeed(d){state.speed=clamp(state.speed+d,1,10);saveSettings();updateStats()}
function restart(){setRunning(false);scrollArea.scrollTop=0;updateProgress();const c=$('#count');let n=3;c.textContent=n;c.classList.add('show');const timer=setInterval(()=>{n--;if(n)c.textContent=n;else{clearInterval(timer);c.textContent='●';setTimeout(()=>{c.classList.remove('show');setRunning(true)},300)}},650)}
function addHistory(text){const clean=(text||'').trim();if(clean.length<3)return;history=history.filter(e=>e.text!==clean);history.unshift({id:Date.now(),text:clean,time:new Date().toISOString()});saveHistory();renderHistory()}
function trashIcon(){const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.setAttribute('viewBox','0 0 24 24');svg.setAttribute('aria-hidden','true');svg.innerHTML='<path d="M4 7h16M9 7V4h6v3M7 7l1 13h8l1-13M10 11v5M14 11v5"/>';return svg}
function renderHistory(){const box=$('#history');box.replaceChildren();if(!history.length){const e=document.createElement('div');e.className='history-empty';e.textContent='Os textos colados aparecerão aqui.';box.append(e);return}history.forEach(entry=>{const item=document.createElement('div');item.className='history-item';const load=document.createElement('button');load.className='load';load.title='Restaurar este roteiro';const title=document.createElement('span');title.textContent=entry.text;const time=document.createElement('small');time.textContent=new Date(entry.time).toLocaleString('pt-BR',{dateStyle:'short',timeStyle:'short'});load.append(title,time);load.onclick=()=>{if(state.text.trim()&&state.text.trim()!==entry.text)addHistory(state.text);state.text=entry.text;editor.value=entry.text;saveText();renderText();scrollArea.scrollTop=0;closePopovers();editor.focus()};const remove=document.createElement('button');remove.className='trash';remove.title='Excluir do histórico';remove.setAttribute('aria-label','Excluir do histórico');remove.append(trashIcon());remove.onclick=()=>{history=history.filter(c=>c.id!==entry.id);saveHistory();renderHistory()};item.append(load,remove);box.append(item)})}
function setPopover(button,pop,open){pop.hidden=!open;button.setAttribute('aria-expanded',String(open))}
function closePopovers(){setPopover(historyButton,historyPopover,false);setPopover(helpButton,helpPopover,false)}
function togglePopover(button,pop){const open=pop.hidden;closePopovers();setPopover(button,pop,open)}
function captureAnchor(){const b=scrollArea.getBoundingClientRect(),y=b.top+b.height*state.cue/100,x=b.left+b.width/2,p=document.caretPositionFromPoint?.(x,y);let node=p?.offsetNode,offset=p?.offset;if(!node&&document.caretRangeFromPoint){const r=document.caretRangeFromPoint(x,y);node=r?.startContainer;offset=r?.startOffset}const ratio=scrollArea.scrollTop/Math.max(1,scrollArea.scrollHeight-scrollArea.clientHeight);if(!node||!reader.contains(node))return{ratio};const r=document.createRange();r.setStart(node,offset);r.setEnd(node,Math.min((node.textContent||'').length,offset+1));return{node,offset,deltaY:r.getBoundingClientRect().top-y,ratio}}
function restoreAnchor(a){if(!a)return;requestAnimationFrame(()=>requestAnimationFrame(()=>{const b=scrollArea.getBoundingClientRect(),y=b.top+b.height*state.cue/100;if(a.node?.isConnected){const r=document.createRange();r.setStart(a.node,a.offset);r.setEnd(a.node,Math.min((a.node.textContent||'').length,a.offset+1));scrollArea.scrollTop+=r.getBoundingClientRect().top-y-a.deltaY}else scrollArea.scrollTop=a.ratio*Math.max(0,scrollArea.scrollHeight-scrollArea.clientHeight);updateProgress()}))}
async function toggleFocus(){closePopovers();const a=captureAnchor();if(document.body.classList.contains('focus')||document.fullscreenElement){if(document.fullscreenElement)await document.exitFullscreen().catch(()=>{});document.body.classList.remove('focus')}else{document.body.classList.add('focus');$('#panel').classList.remove('open');if(document.fullscreenEnabled)await document.documentElement.requestFullscreen().catch(()=>{})}restoreAnchor(a)}
editor.value=state.text;editor.oninput=()=>{state.text=editor.value;saveText();renderText()};editor.addEventListener('paste',()=>setTimeout(()=>addHistory(editor.value),80));editor.onfocus=()=>setRunning(false);
$('#sample').onclick=()=>{if(state.text&&!confirm('Substituir o roteiro atual?'))return;addHistory(state.text);state.text='O teleprompter transforma qualquer roteiro em uma leitura natural diante das câmeras.\n\nVocê ajusta a velocidade da rolagem no seu próprio ritmo, sem perder o contato visual com a lente.\n\nA linha-guia marca o ponto exato onde seus olhos devem focar durante toda a apresentação.\n\nFonte, entrelinha e margens podem ser ajustadas até o texto ficar confortável para ler de longe.\n\nNo modo tela cheia, os controles desaparecem e sobra apenas o roteiro na tela.\n\nArraste o texto com o dedo ou o mouse sempre que precisar voltar ou avançar uma linha.\n\nCada roteiro colado fica salvo no histórico, pronto para ser reaproveitado quando quiser.\n\nVocê também pode espelhar o texto, útil para quem grava com prompter físico e vidro refletor.\n\nIdeal para criadores de conteúdo, professores, palestrantes e qualquer pessoa que apresenta em público.\n\nEm poucos minutos, qualquer pessoa consegue apresentar como um profissional experiente.';editor.value=state.text;saveText();renderText();editor.focus()};
$('#clear').onclick=()=>{if(state.text&&!confirm('Limpar o roteiro?'))return;addHistory(state.text);state.text='';editor.value='';saveText();renderText();editor.focus()};
document.querySelectorAll('[data-k]').forEach(button=>button.onclick=()=>{const k=button.dataset.k,d=Number(button.dataset.d);if(k==='font')state.font=clamp(state.font+d,24,96);if(k==='line')state.line=clamp(Math.round((state.line+d)*100)/100,1.1,2.2);if(k==='margin')state.margin=clamp(state.margin+d,2,24);if(k==='cue')state.cue=clamp(state.cue+d,25,70);applySettings();saveSettings()});
['upper','mirror'].forEach(k=>$(`#${k}`).onchange=e=>{state[k]=e.target.checked;applySettings();saveSettings()});
playButton.onclick=()=>setRunning(!state.running);$('#slow').onclick=()=>changeSpeed(-1);$('#fast').onclick=()=>changeSpeed(1);$('#restart').onclick=restart;$('#focus').onclick=toggleFocus;$('#edit').onclick=()=>{setRunning(false);$('#panel').classList.add('open');setTimeout(()=>editor.focus(),230)};$('#close').onclick=()=>$('#panel').classList.remove('open');
historyButton.onclick=e=>{e.stopPropagation();togglePopover(historyButton,historyPopover)};helpButton.onclick=e=>{e.stopPropagation();togglePopover(helpButton,helpPopover)};historyPopover.onclick=e=>e.stopPropagation();helpPopover.onclick=e=>e.stopPropagation();document.addEventListener('click',closePopovers);
scrollArea.addEventListener('scroll',updateProgress,{passive:true});let drag=null;scrollArea.onpointerdown=e=>{if(e.button!==0)return;setRunning(false);drag={id:e.pointerId,y:e.clientY,top:scrollArea.scrollTop};scrollArea.setPointerCapture(e.pointerId);scrollArea.classList.add('drag');e.preventDefault()};scrollArea.onpointermove=e=>{if(!drag||drag.id!==e.pointerId)return;scrollArea.scrollTop=drag.top-(e.clientY-drag.y);e.preventDefault()};const stop=e=>{if(!drag||drag.id!==e.pointerId)return;drag=null;scrollArea.classList.remove('drag')};scrollArea.onpointerup=stop;scrollArea.onpointercancel=stop;
document.addEventListener('touchmove',e=>{if(!e.target.closest('.scroll,.history,textarea'))e.preventDefault()},{passive:false});['gesturestart','gesturechange'].forEach(type=>document.addEventListener(type,e=>e.preventDefault(),{passive:false}));
document.addEventListener('fullscreenchange',()=>{document.body.classList.toggle('focus',Boolean(document.fullscreenElement));if(!document.fullscreenElement&&state.exitAnchor){restoreAnchor(state.exitAnchor);state.exitAnchor=null}});
document.onkeydown=e=>{if(e.key==='Escape'){closePopovers();state.exitAnchor=captureAnchor()}if(e.target===editor)return;if([' ','ArrowUp','ArrowDown','r','R','f','F'].includes(e.key))e.preventDefault();if(e.key===' ')setRunning(!state.running);if(e.key==='ArrowUp')changeSpeed(1);if(e.key==='ArrowDown')changeSpeed(-1);if(/r/i.test(e.key))restart();if(/f/i.test(e.key))toggleFocus()};window.addEventListener('pagehide',()=>{saveSettings();saveText()});
applySettings();renderText();renderHistory();saveSettings();saveText();requestAnimationFrame(frame);
