'use strict';
const $=s=>document.querySelector(s),clamp=(v,min,max)=>Math.min(max,Math.max(min,v));
const SETTINGS_KEY='teleprompter.settings.v4',TEXT_KEY='teleprompter.currentText.v3',HISTORY_KEY='teleprompter.history.v3';
const WPM=[0,100,140,190,250,320,400,500,620,760,900],defaults={speed:4,font:36,line:1.4,margin:20,cue:50,upper:true,mirror:false};
const SAMPLE='O teleprompter transforma qualquer roteiro em uma leitura natural diante das câmeras.\n\nVocê ajusta a velocidade da rolagem no seu próprio ritmo, sem perder o contato visual com a lente.\n\nA linha-guia marca o ponto exato onde seus olhos devem focar durante toda a apresentação.\n\nFonte, entrelinha e margens podem ser ajustadas até o texto ficar confortável para ler de longe.\n\nNo modo tela cheia, os controles desaparecem e sobra apenas o roteiro na tela.\n\nArraste o texto com o dedo ou o mouse sempre que precisar voltar ou avançar uma linha.\n\nCada roteiro colado fica salvo no histórico, pronto para ser reaproveitado quando quiser.\n\nVocê também pode espelhar o texto, útil para quem grava com prompter físico e vidro refletor.\n\nIdeal para criadores de conteúdo, professores, palestrantes e qualquer pessoa que apresenta em público.\n\nEm poucos minutos, qualquer pessoa consegue apresentar como um profissional experiente.';
const editor=$('#editor'),reader=$('#reader'),scrollArea=$('#scroll'),playButton=$('#play'),restartButton=$('#restart'),historyButton=$('#historyButton'),historyPopover=$('#historyPopover'),helpButton=$('#helpButton'),helpPopover=$('#helpPopover'),toasts=$('#toasts');
function readJSON(key,fallback){try{return JSON.parse(localStorage.getItem(key)||'')||fallback}catch{return fallback}}
function loadStoredSettings(){const current=readJSON(SETTINGS_KEY,null);if(current)return current;const older=readJSON('teleprompter.settings.v3',null)||readJSON('tp2',null);return older?{...older,upper:true}:null}
const storedSettings=loadStoredSettings()||{},legacy=readJSON('tp2',{});
const state={...defaults,...Object.fromEntries(Object.entries(storedSettings).filter(([key,value])=>key in defaults&&value!==undefined&&value!==null)),text:localStorage.getItem(TEXT_KEY)??legacy.text??'',running:false,lastFrame:0,carry:0,exitAnchor:null};
let history=readJSON(HISTORY_KEY,readJSON('tpHistory',[]));
function saveSettings(){try{localStorage.setItem(SETTINGS_KEY,JSON.stringify({speed:state.speed,font:state.font,line:state.line,margin:state.margin,cue:state.cue,upper:state.upper,mirror:state.mirror}))}catch{}}
function saveText(){try{localStorage.setItem(TEXT_KEY,state.text)}catch{}}
function saveHistory(){history=history.slice(0,12);try{localStorage.setItem(HISTORY_KEY,JSON.stringify(history))}catch{history=history.slice(0,6);try{localStorage.setItem(HISTORY_KEY,JSON.stringify(history))}catch{}}}
function showToast(message,{actionLabel,onAction,tone='info',duration=5000}={}){const toast=document.createElement('div');toast.className='toast'+(tone==='danger'?' danger':'');const text=document.createElement('p');text.textContent=message;toast.append(text);const dismiss=()=>{clearTimeout(timer);toast.remove()};if(actionLabel&&onAction){const action=document.createElement('button');action.type='button';action.className='toast-action';action.textContent=actionLabel;action.onclick=()=>{dismiss();onAction()};toast.append(action)}const close=document.createElement('button');close.type='button';close.className='toast-close';close.setAttribute('aria-label','Fechar aviso');close.textContent='×';close.onclick=dismiss;toasts.append(toast);while(toasts.children.length>3)toasts.firstElementChild.remove();toast.append(close);const timer=setTimeout(dismiss,duration);return dismiss}
function countWords(value=state.text){const clean=value.trim();return clean?clean.split(/\s+/).length:0}
function totalSeconds(){return countWords()/WPM[state.speed]*60}
function formatDuration(seconds){if(!seconds||!Number.isFinite(seconds))return'0s';const rounded=Math.max(1,Math.round(seconds)),minutes=Math.floor(rounded/60),rest=rounded%60;return minutes?(rest?`${minutes}min ${rest}s`:`${minutes}min`):`${rest}s`}
function updateStats(){const words=countWords(),empty=words===0;$('#stats').textContent=`${words} ${words===1?'palavra':'palavras'} · ${formatDuration(totalSeconds())}`;$('#speed').textContent=state.speed;$('#speed').title=`${WPM[state.speed]} palavras por minuto`;playButton.disabled=empty;restartButton.disabled=empty;playButton.title=empty?'Cole ou escreva um roteiro para iniciar':'Iniciar leitura'}
function renderText(){const clean=state.text.trim();if(!clean)reader.innerHTML='<p class="empty">Seu roteiro aparece aqui.</p>';else reader.replaceChildren(...clean.split(/\n\s*\n/).map(par=>{const p=document.createElement('p');par.split('\n').forEach((line,index)=>{if(index)p.append(document.createElement('br'));p.append(document.createTextNode(line))});return p}));if(!clean)setRunning(false);updateStats();updateProgress()}
function setText(value,{focus=true}={}){state.text=value;editor.value=value;saveText();renderText();scrollArea.scrollTop=0;if(focus)editor.focus()}
function applySettings(){const root=document.documentElement.style;root.setProperty('--reader-size',`${state.font}px`);root.setProperty('--reader-line',state.line);root.setProperty('--reader-margin',`${state.margin}vw`);root.setProperty('--cue',`${state.cue}%`);reader.classList.toggle('upper',state.upper);reader.classList.toggle('mirror',state.mirror);$('#font').value=state.font;$('#line').value=state.line.toFixed(2);$('#margin').value=state.margin;$('#cueOut').value=state.cue;$('#upper').checked=state.upper;$('#mirror').checked=state.mirror;updateStats()}
function updateProgress(){const max=scrollArea.scrollHeight-scrollArea.clientHeight;$('#progress').style.width=`${max?clamp(scrollArea.scrollTop/max*100,0,100):0}%`}
function setRunning(value){state.running=Boolean(value)&&countWords()>0;playButton.textContent=state.running?'❙❙':'▶';playButton.setAttribute('aria-label',state.running?'Pausar':'Iniciar');if(state.running&&'wakeLock'in navigator)navigator.wakeLock.request('screen').catch(()=>{})}
function pixelsPerSecond(){const max=scrollArea.scrollHeight-scrollArea.clientHeight,duration=totalSeconds();return duration>0?max/duration:0}
function frame(now){const delta=Math.min(40,now-(state.lastFrame||now));state.lastFrame=now;if(state.running){state.carry+=pixelsPerSecond()*delta/1000;if(state.carry>=1){const move=Math.floor(state.carry);scrollArea.scrollTop+=move;state.carry-=move;updateProgress()}if(scrollArea.scrollTop+scrollArea.clientHeight>=scrollArea.scrollHeight-2){setRunning(false);showToast('Fim do roteiro.')}}requestAnimationFrame(frame)}
function changeSpeed(delta){state.speed=clamp(state.speed+delta,1,10);saveSettings();updateStats()}
function restart(){if(!countWords())return;setRunning(false);scrollArea.scrollTop=0;updateProgress();const counter=$('#count');let value=3;counter.textContent=value;counter.classList.add('show');const timer=setInterval(()=>{value--;if(value)counter.textContent=value;else{clearInterval(timer);counter.textContent='●';setTimeout(()=>{counter.classList.remove('show');setRunning(true)},300)}},650)}
function addHistory(text){const clean=(text||'').trim();if(clean.length<3)return false;const exists=history.some(entry=>entry.text===clean);history=history.filter(entry=>entry.text!==clean);history.unshift({id:Date.now(),text:clean,time:new Date().toISOString()});saveHistory();renderHistory();return !exists}
function trashIcon(){const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.setAttribute('viewBox','0 0 24 24');svg.setAttribute('aria-hidden','true');svg.innerHTML='<path d="M4 7h16M9 7V4h6v3M7 7l1 13h8l1-13M10 11v5M14 11v5"/>';return svg}
function renderHistory(){const box=$('#history');box.replaceChildren();historyButton.title=history.length?`Histórico (${history.length})`:'Histórico de roteiros';if(!history.length){const empty=document.createElement('div');empty.className='history-empty';empty.textContent='Os textos colados aparecerão aqui.';box.append(empty);return}history.forEach(entry=>{const item=document.createElement('div');item.className='history-item';const load=document.createElement('button');load.type='button';load.className='load';load.title='Restaurar este roteiro';const title=document.createElement('span');title.textContent=entry.text;const time=document.createElement('small');time.textContent=new Date(entry.time).toLocaleString('pt-BR',{dateStyle:'short',timeStyle:'short'});load.append(title,time);load.onclick=()=>{const previous=state.text;if(previous.trim()&&previous.trim()!==entry.text)addHistory(previous);setText(entry.text);closePopovers();showToast('Roteiro restaurado do histórico.',{actionLabel:'Desfazer',onAction:()=>setText(previous)})};const remove=document.createElement('button');remove.type='button';remove.className='trash';remove.title='Excluir do histórico';remove.setAttribute('aria-label','Excluir do histórico');remove.append(trashIcon());remove.onclick=()=>{const index=history.findIndex(candidate=>candidate.id===entry.id);const [removed]=history.splice(index,1);saveHistory();renderHistory();showToast('Roteiro excluído do histórico.',{tone:'danger',actionLabel:'Desfazer',onAction:()=>{history.splice(index,0,removed);saveHistory();renderHistory()}})};item.append(load,remove);box.append(item)})}
function setPopover(button,popover,open){popover.hidden=!open;button.setAttribute('aria-expanded',String(open))}
function closePopovers(){setPopover(historyButton,historyPopover,false);setPopover(helpButton,helpPopover,false)}
function togglePopover(button,popover){const open=popover.hidden;closePopovers();setPopover(button,popover,open)}
function captureAnchor(){const box=scrollArea.getBoundingClientRect(),y=box.top+box.height*state.cue/100,x=box.left+box.width/2,position=document.caretPositionFromPoint?.(x,y);let node=position?.offsetNode,offset=position?.offset;if(!node&&document.caretRangeFromPoint){const range=document.caretRangeFromPoint(x,y);node=range?.startContainer;offset=range?.startOffset}const ratio=scrollArea.scrollTop/Math.max(1,scrollArea.scrollHeight-scrollArea.clientHeight);if(!node||!reader.contains(node))return{ratio};const range=document.createRange();range.setStart(node,offset);range.setEnd(node,Math.min((node.textContent||'').length,offset+1));return{node,offset,deltaY:range.getBoundingClientRect().top-y,ratio}}
function restoreAnchor(anchor){if(!anchor)return;requestAnimationFrame(()=>requestAnimationFrame(()=>{const box=scrollArea.getBoundingClientRect(),y=box.top+box.height*state.cue/100;if(anchor.node?.isConnected){const range=document.createRange();range.setStart(anchor.node,anchor.offset);range.setEnd(anchor.node,Math.min((anchor.node.textContent||'').length,anchor.offset+1));scrollArea.scrollTop+=range.getBoundingClientRect().top-y-anchor.deltaY}else scrollArea.scrollTop=anchor.ratio*Math.max(0,scrollArea.scrollHeight-scrollArea.clientHeight);updateProgress()}))}
async function toggleFocus(){closePopovers();const anchor=captureAnchor();if(document.body.classList.contains('focus')||document.fullscreenElement){if(document.fullscreenElement)await document.exitFullscreen().catch(()=>{});document.body.classList.remove('focus')}else{document.body.classList.add('focus');$('#panel').classList.remove('open');if(document.fullscreenEnabled)await document.documentElement.requestFullscreen().catch(()=>{})}restoreAnchor(anchor)}
editor.value=state.text;editor.oninput=()=>{state.text=editor.value;saveText();renderText()};editor.addEventListener('paste',()=>setTimeout(()=>{if(addHistory(editor.value))showToast('Roteiro salvo no histórico.')},80));editor.onfocus=()=>setRunning(false);
$('#sample').onclick=()=>{const previous=state.text;if(previous.trim())addHistory(previous);setText(SAMPLE);showToast('Texto de teste carregado.',{actionLabel:'Desfazer',onAction:()=>setText(previous)})};
$('#clear').onclick=()=>{const previous=state.text;if(!previous.trim()){showToast('O roteiro já está vazio.');return}addHistory(previous);setText('');showToast('Roteiro limpo.',{tone:'danger',actionLabel:'Desfazer',onAction:()=>setText(previous)})};
document.querySelectorAll('[data-k]').forEach(button=>button.onclick=()=>{const key=button.dataset.k,delta=Number(button.dataset.d);if(key==='font')state.font=clamp(state.font+delta,24,96);if(key==='line')state.line=clamp(Math.round((state.line+delta)*100)/100,1.1,2.2);if(key==='margin')state.margin=clamp(state.margin+delta,2,24);if(key==='cue')state.cue=clamp(state.cue+delta,25,70);applySettings();saveSettings()});
['upper','mirror'].forEach(key=>$(`#${key}`).onchange=event=>{state[key]=event.target.checked;applySettings();saveSettings()});
playButton.onclick=()=>{if(!countWords())return;setRunning(!state.running)};$('#slow').onclick=()=>changeSpeed(-1);$('#fast').onclick=()=>changeSpeed(1);restartButton.onclick=restart;$('#focus').onclick=toggleFocus;$('#edit').onclick=()=>{setRunning(false);$('#panel').classList.add('open');setTimeout(()=>editor.focus(),230)};$('#close').onclick=()=>$('#panel').classList.remove('open');
historyButton.onclick=event=>{event.stopPropagation();togglePopover(historyButton,historyPopover)};helpButton.onclick=event=>{event.stopPropagation();togglePopover(helpButton,helpPopover)};historyPopover.onclick=event=>event.stopPropagation();helpPopover.onclick=event=>event.stopPropagation();document.addEventListener('click',closePopovers);
scrollArea.addEventListener('scroll',updateProgress,{passive:true});let drag=null;scrollArea.onpointerdown=event=>{if(event.button!==0)return;setRunning(false);drag={id:event.pointerId,y:event.clientY,top:scrollArea.scrollTop};scrollArea.setPointerCapture(event.pointerId);scrollArea.classList.add('drag');event.preventDefault()};scrollArea.onpointermove=event=>{if(!drag||drag.id!==event.pointerId)return;scrollArea.scrollTop=drag.top-(event.clientY-drag.y);event.preventDefault()};const stopDrag=event=>{if(!drag||drag.id!==event.pointerId)return;drag=null;scrollArea.classList.remove('drag')};scrollArea.onpointerup=stopDrag;scrollArea.onpointercancel=stopDrag;
document.addEventListener('touchmove',event=>{if(!event.target.closest('.scroll,.history,.toast,textarea'))event.preventDefault()},{passive:false});['gesturestart','gesturechange'].forEach(type=>document.addEventListener(type,event=>event.preventDefault(),{passive:false}));
document.addEventListener('fullscreenchange',()=>{document.body.classList.toggle('focus',Boolean(document.fullscreenElement));if(!document.fullscreenElement&&state.exitAnchor){restoreAnchor(state.exitAnchor);state.exitAnchor=null}});
document.onkeydown=event=>{if(event.key==='Escape'){closePopovers();state.exitAnchor=captureAnchor()}if(event.target===editor)return;if([' ','ArrowUp','ArrowDown','r','R','f','F'].includes(event.key))event.preventDefault();if(event.key===' '&&countWords())setRunning(!state.running);if(event.key==='ArrowUp')changeSpeed(1);if(event.key==='ArrowDown')changeSpeed(-1);if(/^r$/i.test(event.key))restart();if(/^f$/i.test(event.key))toggleFocus()};window.addEventListener('pagehide',()=>{saveSettings();saveText()});
applySettings();renderText();renderHistory();saveSettings();saveText();requestAnimationFrame(frame);
